spring:
  application:
    name: clients-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/clientsdb
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  webflux:
    log-request-details: true

logging:
  level:
    root: INFO
    org.nttdata.bank.clients: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/clients-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  timelimiter:
    instances:
      clientsService:
        timeout-duration: 2s
  circuitbreaker:
    instances:
      clientsService:
        sliding-window-size: 10
        failure-rate-threshold: 50

security:
  jwt:
    secret-base64: c3VwZXItc2VjcmV0LWtleS13aXRoLWxlbmd0aC1mb3Itand0LTMxLXNpemU=

server:
  port: 8079

